version: "3.9"
services:
  api:
    build: ./backend-nest
    container_name: api
    restart: unless-stopped
    command: npm run start
    networks:
      - docker-sashaperk-network

  frontend:
    build: ./frontend-react
    container_name: frontend
    restart: unless-stopped
    networks:
      - docker-sashaperk-network

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - docker-sashaperk-network


networks:
  docker-sashaperk-network:
    driver: bridge